[workspace]
members = ["packages/*/*"]
resolver = "2"

[workspace.package]
authors = ["Rust For Web <info@rustforweb.org>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/RustForWeb/react"
version = "0.0.1"

[workspace.dependencies]
leptos = { version = "0.6.12" }
