[workspace]
members = ["packages/*/*"]
resolver = "2"

[workspace.package]
authors = ["Rust for Web <info@rustforweb.org>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/RustForWeb/react"
version = "0.0.1"

[workspace.dependencies]
leptos = { version = "0.8.0" }
